services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=challenge'
      - 'POSTGRES_USER=challenge'
      - 'POSTGRES_PASSWORD=fitiz-challenge'
    ports:
      - '5432:5432'