apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-service
spec:
  template:
    spec:
      containers:
        - name: challenge-service
          image: europe-west10-docker.pkg.dev/fitiz-app/fitiz/challenge-service-image:0.0.1
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: fitiz-challenge-service
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: fitiz-challenge-service
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: fitiz-challenge-service
                  key: database
          resources:
            requests:
              memory: "500Mi"
            limits:
              memory: "1500Mi"
        - name: cloud-sql-proxy
          command:
            - /cloud_sql_proxy
            - -instances=fitiz-app:europe-west3:challenge-service-db=tcp:0.0.0.0:5432