apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-service
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: cloud-sql-proxy
          command:
            - /cloud_sql_proxy
            - -instances=fitiz-app:europe-west3:challenge-service-db=tcp:0.0.0.0:5432
        - name: challenge-service
          image: europe-west10-docker.pkg.dev/fitiz-app/fitiz/challenge-service-image:0.0.1
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: challenge-service-infra
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: challenge-service-infra
                  key: SPRING_DATASOURCE_PASSWORD
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: challenge-service-infra
                  key: SPRING_DATASOURCE_URL
          resources:
            requests:
              memory: "500Mi"
            limits:
              memory: "1500Mi"
