apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-service
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: cloud-sql-proxy
          resources:
            limits:
              memory: "600Mi"
              cpu: "250m"
            requests:
              memory: "600Mi"
              cpu: "250m"
          args:
            - "--port=5432"
            - "fitiz-app:europe-west3:challenge-service-db"
        - name: challenge-service
          image: europe-west10-docker.pkg.dev/fitiz-app/fitiz/challenge-service-image-dev:0.0.1
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: challenge-service-infra
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: challenge-service-infra
                  key: SPRING_DATASOURCE_PASSWORD
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: challenge-service-infra
                  key: SPRING_DATASOURCE_URL
          resources:
            limits:
              memory: "600Mi"
              cpu: "250m"
            requests:
              memory: "600Mi"
              cpu: "250m"