apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

commonLabels:
  app: challenge-service
  env: dev

resources:
  - ../../base
  - config.yaml

patchesStrategicMerge:
  - deployment-patch.yaml