apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

commonLabels:
  app: challenge-service
  env: dev

resources:
  - ../../base
  - config.yaml

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: challenge-service
      namespace: dev
      version: v1