apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-service
spec:
  selector:
    matchLabels:
      app: challenge-service
  template:
    spec:
      containers:
        - name: challenge-service
          image: challenge-service-image
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.22.0
          securityContext:
            runAsNonRoot: true
      dnsPolicy: ClusterFirst
      serviceAccountName: fitiz-sa
