apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-service
spec:
  selector:
    matchLabels:
      app: challenge-service
  replicas: 2
  template:
    spec:
      containers:
        - name: challenge-service
          image: challenge-service-image
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 3
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: fitiz-challenge-service
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: fitiz-challenge-service
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: fitiz-challenge-service
                  key: database
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.0
          securityContext:
            runAsNonRoot: true
      dnsPolicy: ClusterFirst
      serviceAccountName: fitiz-sa
