apiVersion: v1
kind: Service
metadata:
  name: challenge-service
spec:
ports:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: challenge-service
  type: LoadBalancer
